apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.confignode.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.confignode.name }}
spec:
  ports:
  - port: 80
    name: rpc
  clusterIP: None
  selector:
    app: {{ .Values.confignode.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.confignode.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.confignode.name }}
  serviceName: {{ .Values.confignode.name }}-svc
  replicas: {{ .Values.confignode.nodeCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.confignode.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: confignode
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        command: ["/bin/bash", "-c", "/iotdb/start-confignode.sh"]
        resources:
          requests:
            memory: {{ .Values.confignode.resources.requests.memory }}
            cpu: {{ .Values.confignode.resources.requests.cpu }}
          limits:
            memory: {{ .Values.confignode.resources.limits.memory }}
            cpu: {{ .Values.confignode.resources.limits.cpu }}
        ports:
        - containerPort: 80
          name: web
        - containerPort: 22277
          name: internal
        - containerPort: 22278
          name: consensus
        volumeMounts:
        - name: data
          mountPath: {{ .Values.confignode.dataDir }}
        - name: config
          mountPath: /iotdb/conf_tmp
      volumes:
      - name: config
        configMap:
          name: {{ .Values.confignode.name }}-cm
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.className }}
      resources:
        requests:
          storage: {{ .Values.confignode.storageCapacity }}