apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.datanode.name }}-svc
  labels:
    app: {{ .Values.datanode.name }}
spec:
  ports:
  - port: 80
    name: rpc
  clusterIP: None
  selector:
    app: {{ .Values.datanode.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.datanode.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.datanode.name }}
  serviceName: {{ .Values.datanode.name }}-svc
  replicas: {{ .Values.datanode.nodeCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.datanode.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: datanode
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        command: ["/bin/bash", "-c", "/iotdb/start-datanode.sh"]
        resources:
          requests:
            memory: {{ .Values.datanode.resources.requests.memory }}
            cpu: {{ .Values.datanode.resources.requests.cpu }}
          limits:
            memory: {{ .Values.datanode.resources.limits.memory }}
            cpu: {{ .Values.datanode.resources.limits.cpu }}
        ports:
        - containerPort: 80
          name: web
        - containerPort: 6667
          name: rpc
        - containerPort: 9003
          name: internal
        - containerPort: 8777
          name: mpp-exchange
        - containerPort: 50010
          name: schema-cons
        - containerPort: 40010
          name: data-cons
        volumeMounts:
        - name: data
          mountPath: {{ .Values.datanode.dataDir }}
        - name: config
          mountPath: /iotdb/conf_tmp
      volumes:
      - name: config
        configMap:
          name: {{ .Values.datanode.name }}-cm
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.className }}
      resources:
        requests:
          storage: {{ .Values.datanode.storageCapacity }}