apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.datanode.name }}-cm
  namespace: {{ .Values.namespace }}
data:
  iotdb-datanode.properties: |
    dn_rpc_address=<HOSTNAME>.{{ .Values.datanode.name }}-svc.{{ .Values.namespace }}
    dn_internal_address=<HOSTNAME>.{{ .Values.datanode.name }}-svc.{{ .Values.namespace }}
    dn_target_config_node_list={{ .Values.confignode.name }}-0.{{ .Values.confignode.name }}-svc.{{ .Values.namespace }}:22277