apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: iotdb-node-port-svc
spec:
  type: NodePort
  selector:
    app: {{ .Values.datanode.name }}
  ports:
  - port: 6667
    targetPort: 6667
    nodePort: 32667