apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.confignode.name }}-svc
  labels:
    app: {{ .Values.confignode.name }}
spec:
  ports:
  - port: 80
    name: rpc
  clusterIP: None
  selector:
    app: {{ .Values.confignode.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.confignode.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.confignode.name }}
  serviceName: {{ .Values.confignode.name }}-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.confignode.name }}
    spec:
      terminationGracePeriodSeconds: 100
      containers:
      - name: confignode
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "azurefile"
      resources:
        requests:
          storage: 10Mi