apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.datanode.name }}-svc
  labels:
    app: {{ .Values.datanode.name }}
spec:
  ports:
  - port: 80
    name: rpc
  clusterIP: None
  selector:
    app: {{ .Values.datanode.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.datanode.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.datanode.name }}
  serviceName: {{ .Values.datanode.name }}-svc
  replicas: {{ .Values.datanode.nodeCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.datanode.name }}
    spec:
      terminationGracePeriodSeconds: 100
      containers:
      - name: datanode
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        - containerPort: 6667
          name: dn_rpc_port
        - containerPort: 9003
          name: dn_internal_port
        - containerPort: 8777
          name: dn_mpp_data_exchange_port
        - containerPort: 50010
          name: dn_schema_region_consensus_port
        - containerPort: 40010
          name: dn_data_region_consensus_port
        volumeMounts:
        - name: data
          mountPath: {{ .Values.datanode.dataDir }}
        - name: config
          mountPath: /iotdb/conf_tmp
      volumes:
      - name: config
        configMap:
          name: {{ .Values.datanode.name }}-cm
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "azurefile"
      resources:
        requests:
          storage: 10Mi