# Default values for iotdb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "iotdb"
fullnameOverride: "iotdb"
namespace: iotdb-cluster

image:
  repository: docker.io/xingtanzjr/iotdb-cluster
  pullPolicy: IfNotPresent
  tag: 0.1.9

storage:
  className: edge-rbd

datanode:
  name: datanode
  nodeCount: 3
  dataDir: /iotdb/data
  storageCapacity: 200Gi
  resources:
    requests:
      memory: "16Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "8000m"

confignode:
  name: confignode
  nodeCount: 3
  dataDir: /iotdb/data
  storageCapacity: 10Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "1000m"
    limits:
      memory: "8Gi"
      cpu: "2000m"
  configNodeConsensusProtocolClass: org.apache.iotdb.consensus.ratis.RatisConsensus
  schemaReplicationFactor: 3
  schemaRegionConsensusProtocolClass: org.apache.iotdb.consensus.ratis.RatisConsensus
  dataReplicationFactor: 3
  dataRegionConsensusProtocolClass: org.apache.iotdb.consensus.multileader.MultiLeaderConsensus
