# Default values for iotdb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "iotdb"
fullnameOverride: "iotdb"
namespace: iotdb-cluster

image:
  repository: docker.io/xingtanzjr/iotdb-cluster
  pullPolicy: IfNotPresent
  tag: rel_1.0

storage:
  className: local-storage

datanode:
  name: datanode
  nodeCount: 3
  dataDir: /iotdb/data
  storageCapacity: 20Gi

confignode:
  name: confignode
  nodeCount: 1
  dataDir: /iotdb/data
  storageCapacity: 1Gi
  configNodeConsensusProtocolClass: org.apache.iotdb.consensus.ratis.RatisConsensus
  schemaReplicationFactor: 1
  schemaRegionConsensusProtocolClass: org.apache.iotdb.consensus.ratis.RatisConsensus
  dataReplicationFactor: 3
  dataRegionConsensusProtocolClass: org.apache.iotdb.consensus.iot.IoTConsensus
