# Default values for iotdb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "iotdb"
fullnameOverride: "iotdb"

image:
  repository: docker.io/xingtanzjr/iotdb-cluster
  pullPolicy: IfNotPresent
  tag: 0.1.7

datanode:
  name: iotdb-datanode
  nodeCount: 3
  dataDir: /iotdb/data

confignode:
  name: iotdb-confignode
  nodeCount: 3
  dataDir: /iotdb/data
  configNodeConsensusProtocolClass: org.apache.iotdb.consensus.ratis.RatisConsensus
  schemaReplicationFactor: 1
  schemaRegionConsensusProtocolClass: org.apache.iotdb.consensus.simple.SimpleConsensus
  dataReplicationFactor: 1
  dataRegionConsensusProtocolClass: org.apache.iotdb.consensus.simple.SimpleConsensus
